api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    # The title of the API.
    title: 'API BileMo'
    # The description of the API.
    description: "List of BileMo products as well as customer user management"
    # The version of the API.
    version: '1.0.0'
    defaults:
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin', 'Accept' ]
            etag: true
    http_cache:
        public: false
